### ISSUE TITLE
Error: Get-CRMSystemSettings : Cannot bind argument to parameter 'Name' because it is null.

### ISSUE THREAD

**Issue by LeftCoastBC** [seanmcne/Microsoft.Xrm.Data.PowerShell#338] opened 2018-10-19 16:15 UTC
Starting in version 2.8.1 I get the error message "Get-CRMSystemSettings : Cannot bind argument to parameter 'Name' because it is null." when running Get-CRMSystemSettings. In version 2.8.0 I didn't have this issue.

The Command completes and receives a number of system settings, but this error always shows up twice. I've tested this on 2 Environments.

Connecting to CRMOnline Version 9.0.2.54

```
PS>Get-CRMSystemSettings -conn $Conn
Add-Member : Cannot bind argument to parameter 'Name' because it is null.
At C:\Users\[me]\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.1\Microsoft.Xrm.Data.Powershell.psm1:3520 char:71
+ ... mber -InputObject $psobj -MemberType NoteProperty -Name $name -Value  ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand
 
Add-Member : Cannot bind argument to parameter 'Name' because it is null.
At C:\Users\[me]\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.1\Microsoft.Xrm.Data.Powershell.psm1:3520 char:71
+ ... mber -InputObject $psobj -MemberType NoteProperty -Name $name -Value  ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand
```

**Comment by seanmcne** [comment] 2018-10-20 00:54
Duplicate of #336 fixed in #337

**Closed** 2018-10-20 00:55 UTC
Labels: duplicate
