### ISSUE TITLE
Export-CrmSolution doesn't throw if the operation fails

### ISSUE THREAD

**Issue by ian-moore** [seanmcne/Microsoft.Xrm.Data.PowerShell#191] opened 2017-02-28 15:39 UTC
The try catch block in this function does `Write-Error` instead of `throw`, which means a failed export was continuing to run my script unless I add `-ErrorPreference Stop` argument and catch/re-throw myself.

Should this be throwing instead? Looking at the other commands, I can't see a pattern as to which use `throw` and which use `Write-Error`. I can submit a pull request for the intended behavior.

**Comment by amervitz** [comment] 2017-02-28 16:42
My preference is the use of `Write-Error` instead of `throw`. I have used `Write-Error` in functions I've added and was planning to in additional ones I'm working on. `Write-Error` is better when dealing with pipeline scenarios so that an individual failed item in a collection still allows other items to be processed. You can inspect the `$Error` collection and deal with failed items afterwards too. When feasible, I would advocate for existing instances of `throw` to be converted to `Write-Error` when they aren't truly terminating errors.

**Comment by ian-moore** [comment] 2017-02-28 20:21
@amervitz I follow you. In this case, the function was `Export-CrmSolution` and the export was unable to complete due to a failure in Dynamics - should that not be a terminating error? If there is to be a difference between non-terminating and terminating errors, maybe having a try/catch around the entire function body that does `Write-Error` is not appropriate.

**Comment by amervitz** [comment] 2017-03-01 02:29
@ian-moore it's a somewhat subjective topic but I personally prefer `Write-Error` as a caller because depending upon the scenario at hand I can, without extra effort, by default let processing continue when an error occurs, or I may want to force the script to stop as you've explained with `-ErrorPreference Stop`. If I really don't care about an error I can use `-ErrorPreference SilentlyContainue`. When a function`throw`s, you have no choice as a caller but to catch exceptions which IMO is less flexible and muddies up the code (especially in an interactive ISE session), and goes against the PowerShell grain of trying to continue processing. I find most PowerShell cmdlets tend to use `Write-Error` when a problem occurs whereas .NET classes have no choice but to `throw`.

I've actually had a problematic solution export recently, and with the current behavior only one solution was failing to export but the other ones still exported. This suited my needs because I was still in an exploratory development setting where I was testing the export of multiple solutions and so I could see which ones succeeded and failed without having to add extra try/catch logic to let the subsequent solutions get exported. When I was finished my code and using the script in a production setting where I didn't want to continue any further processing when a solution export or any other kind of error occured, I set the global variable `$ErrorActionPreference = 'Stop'` at the very top of the top level .ps1 file.

I don't see a problem myself with the current `Export-CrmSolution` error handling besides a minor change where it could `Write-Error $_` instead of `Write-Error $_.Exception`, to provide the full error object which might have extra information that is currently being swallowed.

It's hard for me to think of a scenario when `throw` should be used instead of `Write-Error`, it would have to be something completely catastrophic where you _really_ don't want someone to try doing anything else afterwards by default.

**Comment by amervitz** [comment] 2017-03-03 08:13
I've found some MSDN documentation with some guidelines on error reporting and choosing whether to generate a terminating error or a nonterminating error , see [Cmdlet Error Reporting](https://msdn.microsoft.com/en-us/library/ms714412(v=vs.85).aspx).

The guideline that seems to most closely relate to Export-CrmSolution is:

> Cmdlets that can accept only 0-1 input objects and generate only 0-1 output objects should treat errors as terminating errors and generate terminating exceptions.

This seems to suggest that a terminating error is appropriate in this situation since it is (if I'm interpreting properly) taking only 1 input object (i.e. no pipeline variables or collection based parameters). However, I'm inclined to also take into consideration how many times a cmdlet might be invoked in succession and not just the number of input objects, similar to what the other guidelines refer to in the scenarios where multiple inputs are accepted and are more often suggested to be non-terminating. In this case, invoking `Export-CrmSolution` multiple times in succession in a loop is a reasonable scenario (i.e. treat as non-terminating), whereas a function like `Get-CrmTimeZones` is one that is more likely a one-time action (i.e. treat as terminating) since it doesn't have any parameters that would change the return value (although you could technically invoke it multiple times with different CRM connection objects and export the time zones from multiple organizations in succession, but perhaps this is not common and the connection object shouldn't be included in the decision).

All that said, I'm of the opinion this cmdlet is OK from an error handling standpoint and suits my needs 😄, but do think it is good to be mindful of this.

**Comment by amervitz** [comment] 2017-03-03 13:36
@ian-moore does the returned error object when failing to import the solution (`$Error[0]` if I'm not mistaken when dealing with just one failure to inspect), contain enough information to identify the solution that failed? If not, specifying the `-TargetObject` parameter on the existing call to `Write-Error` could be a good addition to help with post-processing error handling of import failures.

**Comment by ian-moore** [comment] 2017-03-07 19:59
Thanks for the comprehensive feedback @amervitz , my situation is running this as an automated deployment which is why I am looking for any error to always throw. Maybe setting `$ErrorActionPreference = 'Stop'` at the script level is all I need. I am trying to avoid needing to try/catch with every cmdlet I'm invoking.

**Comment by amervitz** [comment] 2017-03-07 20:14
@ian-moore yes that should work, all exceptions and errors should then make your script stop at either of their first occurrence. You may want to close this issue if that works.

**Comment by ian-moore** [comment] 2017-03-13 14:41
Is there a way to see in the command help if it will throw or not? Having that info easily available could help indicate how/when to handle errors

**Comment by amervitz** [comment] 2017-03-13 15:38
I'm not aware of any built in approach or documentation convention in PowerShell for describing this. I think that would be a manual documentation effort to describe the error/exception behavior to each command's help, such as in the NOTES section.

**Comment by seanmcne** [comment] 2017-03-14 03:19
Are you talking "all up" in powershell - or do you mean if a specific command in this module will throw?  the idea would be that any fatal exception would throw an exception - we want it to fail when it fails versus return null or do something benign that isn't actionable.

**Comment by ian-moore** [comment] 2017-03-14 13:52
I was referring to commands in this module. I think the discussion between @amervitz and myself is what constitutes a "fatal" error and how they should be handled. Taking action on `Write-Error` can be done but requires manipulating the ErrorPreference

**Comment by seanmcne** [comment] 2017-03-20 00:58
@ian-moore is the ask to change the below over to throw $_.Exception versus Write-Error?  

For reference I did find a pretty good stackoverflow write up which basically says the preference (for us) should be to throw - but a script designer / caller / consumer can change the error action on the function/cmdlet execution to interprit how they want to address any write-error's. 
![image](https://cloud.githubusercontent.com/assets/2292260/24086500/6f93653c-0cde-11e7-80d8-18df240d00aa.png)


References in our code: 
Import-CrmSolution 
![image](https://cloud.githubusercontent.com/assets/2292260/24086470/e4e6b204-0cdd-11e7-939d-30d08ea5acff.png)

And Import-CrmSolutionAsync: 
![image](https://cloud.githubusercontent.com/assets/2292260/24086481/1ade63a2-0cde-11e7-855a-51cf5c477c87.png)

**Comment by ian-moore** [comment] 2017-03-20 18:08
> is the ask to change the below over to throw $_.Exception versus Write-Error?

Yes, that is my ask. The discussion on this issue does illuminate some pros & cons to both approaches, but I think my personal preference would still be towards throwing during a solution export. It seems that the documented best practice lean that way as well.

**Comment by vk11714** [comment] 2017-04-12 16:18
Is there anyway to export the default solution? I get an error thrown when I try that.

Export-CrmSolution : System.Management.Automation.MethodException: Cannot find an overload for "ExecuteCrmOrganizationRequest" and 
the argument count: "1".
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
At line:1 char:1
+ Export-CrmSolution -SolutionName "Default" -SolutionFilePath C:\Temp  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-CrmSolution

**Comment by amervitz** [comment] 2017-04-12 22:07
@vk11714 which version of the module are you using? I'm unable to reproduce this error message on 2.5 or with the code in master branch. If you could provide the full command used it would be helpful to see if there's a specific set of parameters that triggers this.

As an aside I always hit the 2 minute timeout being addressed in #183 when trying to export the default solution.

**Comment by vk11714** [comment] 2017-04-17 21:08
Hrm, I'm not sure what I did wrong but it seems to be working now.

Do this powershell cmdlets work in CRM 2011 aswell? I am mainly interested in import/export crmsolution.

Thanks!

**Comment by seanmcne** [comment] 2017-04-18 00:11
Yep currently v8.2 still allows for crm 2011 connectivity so this should work (the message hasn't changed, at least as far as I can remember). Glad it's working now!

**Closed by seanmcne** 2017-04-18 00:11 UTC
Labels: enhancement, question
