### ISSUE TITLE
Calling "ResetLocalMetadataCache" results in error when executing next meta-data query

### ISSUE THREAD

**Issue by thuld** [seanmcne/Microsoft.Xrm.Data.PowerShell#187] opened 2017-02-22 09:17 UTC
The following code yields an error:
````
$oneUrl = 'https://foobar1.crm4.dynamics.com';
$twoUrl = 'https://foobar2.crm4.dynamics.com';

try {
    # create connection first CRM instance (production)
    $conn = Connect-CrmOnline -Credential $credentials -ServerUrl $oneUrl;

    $entity = 'lead';
    $field = 'description';

    $allAttrMetadata1 = Get-CrmEntityAttributes -EntityLogicalName $entity -conn $conn;

    $conn.ResetLocalMetadataCache($entity);

    # create connection second CRM instance (sandbox)
    $conn = Connect-CrmOnline -Credential $credentials -ServerUrl $twoUrl;



    $allAttrMetadata2 = Get-CrmEntityAttributes -EntityLogicalName $entity -conn $conn;
}
catch {
    Write-Host -ForegroundColor Red $conn.LastCrmError;
}

````

Error ($conn.LastCrmError): 
````
************ Exception getting metadata info from CRM   : Der Wert darf nicht NULL sein.
Parametername: v1
````

**Comment by seanmcne** [comment] 2017-02-23 14:36
Duplicate of #188

**Closed by seanmcne** 2017-02-23 14:36 UTC
Labels: duplicate
