### ISSUE TITLE
Issues with Invoke-CrmRecordWorkflow

### ISSUE THREAD

**Issue by simonjpickering** [seanmcne/Microsoft.Xrm.Data.PowerShell#194] opened 2017-03-16 08:10 UTC
Currently we have two different O365 tenants with the same version of Dynamics running on both.. Invoking the Invoke-CrmRecordWorkflow for a workflow against a contact Entity works fine for the one tenant and returns a GUID for the workflow that was initiated. On the other tenant the Invoke-CrmRecordWorkflow appears to run successfully but the GUID returned is a value of all zeros. When looking at the Dynamics 365 backend you see no evidence of the workflow being called. Firstly, is there some setting in the Dynamics 365 environment that would cause this issue and secondly, should the Invoke-CrmRecordWorkflow command indicate an error if this is the case as the workflow was not called successfully?

**Comment by amervitz** [comment] 2017-03-19 01:03
@simonjpickering is it the same workflow being invoked on each D365 instance? Also, is the workflow activated on the problematic instance?

**Comment by seanmcne** [comment] 2017-03-20 00:39
I suspect it may be related to #167 - @simonjpickering can you check the $conn.LastCrmException to see if it matches #167?

**Comment by simonjpickering** [comment] 2017-03-20 09:31
Ok, I've checked the return status from the workflow $conn.LastCrmException and it states the following:

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Workflow must be in Published state

I've checked the permissions for the workflow and it's owned by the user that I'm using to call it and the workflow is in the same owning business unit. The user calling the workflow has system administrator role too.

The workflow is activated and when I look at the dependencies in the workflow they all show as published.

I'm struggling at the moment to see what is causing this.

**Comment by seanmcne** [comment] 2017-03-20 13:57
@simonjpickering sorry for referring you to that bug, I just re-read the contents and realized I didn't put the error message in. The error I received was the same as yours - it was finding a duplicate workflow with the same name which wasn't published.  

Check #167 again as I just updated a proposed script to test. If your workflow executes using this script I think we'll have a fix for you soon (as we'll avoid using the out of box Xrm Tooling workflow execution until that bug is fixed in Xrm Tooling).  I suspect this script may not show you the duplicate it's running into because it's using a more specific fetch statement to find the process but it would still be good to test. 

Thanks!

**Comment by simonjpickering** [comment] 2017-03-21 09:21
Hi, testing with the script provided in #167 worked, the workflow was executed without issue - I called the script a number of times and it worked successfully. Falling back to the standard Invoke-CrmRecordWorkflow showed the same failure. I still don't understand why we only get this issue in certain CRM instances though.

**Comment by seanmcne** [comment] 2017-03-21 13:09
From what I've looked at the error is Linked to entities that support sla's (cases) and those sla Workflows appear to somehow be returned by whatever retrieve xrm tooling is using behind the  scenes - if those sla Workflows aren't there I haven't been able to repro the issue (though there could be other reasons for this error that I haven't encountered). I'll replace our existing logic that uses xrm tooling with the logic in the linked issue. We should have this fixed in the 2.6 release.

**Comment by seanmcne** [comment] 2017-07-17 22:59
Closing as duplicate of #167

@simonjpickering thanks for confirming the proposed solution in #167 will work!

**Closed by seanmcne** 2017-07-17 22:59 UTC
Labels: bug, duplicate
