### ISSUE TITLE
Creating Subsequent connections to different instances remain fixed to the original instance

### ISSUE THREAD

**Issue by thuld** [seanmcne/Microsoft.Xrm.Data.PowerShell#188] opened 2017-02-22 09:34 UTC
We have two CRM instance. The max. length value for attribute "description" (entity lead) is different in these two CRM online instances, but the following code returns in both case the max. length of the first CRM instance:

````
$oneUrl = 'https://foobar1.crm4.dynamics.com';
$twoUrl = 'https://foobar2.crm4.dynamics.com';

# create connection first CRM instance (production)
$conn = Connect-CrmOnline -Credential $credentials -ServerUrl $oneUrl;

$entity = 'lead';
$field = 'description';

$meta1 = Get-CrmEntityAttributeMetadata -EntityLogicalName $entity -FieldLogicalName $field -conn $conn;
Write-Host -ForegroundColor Yellow "Max. Length First CRM Instance: '$($meta1.MaxLength)'" 

# create connection second CRM instance (sandbox)
$conn = Connect-CrmOnline -Credential $credentials -ServerUrl $twoUrl;

$conn.ResetLocalMetadataCache($entity);

$meta2 = Get-CrmEntityAttributeMetadata -EntityLogicalName $entity -FieldLogicalName $field -conn $conn;
Write-Host -ForegroundColor Yellow "Max. Length Second CRM Instance: '$($meta2.MaxLength)'";
``

**Comment by kenakamu** [comment] 2017-02-23 01:49
Try creating separate connection parameter rather than using $conn for both.

**Comment by thuld** [comment] 2017-02-23 08:49
I modified my code (see below) but the outcome is the same. In both cases are the meta-data of the first CRM instance used. 

A developed a script 2-3 month ago using version 2.3 or 2.2 (SDK version 8.1) and that was working as expected. I assume this problem was introduced in the latest SDK version. 

````
$oneUrl = 'https://foobar1.crm4.dynamics.com';
$twoUrl = 'https://foobar2.crm4.dynamics.com';

# create connection first CRM instance (production)
$conn1 = Connect-CrmOnline -Credential $credentials -ServerUrl $oneUrl;

$entity = 'lead';
$field = 'description';


# $meta1 = $conn1.GetEntityAttributeMetadataForAttribute($entity, $field);
$meta1 = Get-CrmEntityAttributeMetadata -EntityLogicalName $entity -FieldLogicalName $field -conn $conn1;
Write-Host -ForegroundColor Yellow "Max. Length First CRM Instance: '$($meta1.MaxLength)'" 

# create connection second CRM instance (sandbox)
$conn2 = Connect-CrmOnline -Credential $credentials -ServerUrl $twoUrl;

$conn1.ResetLocalMetadataCache($entity);
$conn2.ResetLocalMetadataCache($entity);

# $meta2 = $conn2.GetEntityAttributeMetadataForAttribute($entity, $field);
$meta2 = Get-CrmEntityAttributeMetadata -EntityLogicalName $entity -FieldLogicalName $field -conn $conn2;
Write-Host -ForegroundColor Yellow "Max. Length Second CRM Instance: '$($meta2.MaxLength)'";
````

**Comment by seanmcne** [comment] 2017-02-23 14:41
Renaming this to match the root cause of the issue, also will get a fix checked in for the next release.  The scope is only when working with two CRM Instances in the same powershell session/process.  Luckily the latest 8.2 library fixed a quirk with connection string based connections (which we use) and we can now tell it to create separate instances of the connection.  CrmServiceClient treats the connections like a singleton unless this parameter is set to true - in that case it will ensure new connections completely overwrite the first. 

``` Powershell 
#RequireNewInstance=True
#updated connection string 
$connectionString = "AuthType=Office365;RequireNewInstance=True;Username=$userName;Password=$password;Url=$ServerUrl"
````

**Comment by thuld** [comment] 2017-02-24 11:54
I have updated my local version of file "Microsoft.Xrm.Data.PowerShell.psm1" in the following way:

````
# See bug #188
# https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/issues/188
# $connectionString = "AuthType=Office365;Username=$userName; Password=$password;Url=$ServerUrl"
$connectionString = "AuthType=Office365;RequireNewInstance=True;Username=$userName;Password=$password;Url=$ServerUrl"
````

... but my code is still not working as expected (returns the meta-data values of the first instance):
````
Import-Module Microsoft.Xrm.Data.Powershell

# Office 365 credentials are stored on disk (encrypted)
$credentials = Import-Clixml -Path (Join-Path (Split-Path $profile) office365.ps1.credential)

$oneUrl = 'https://foobar1.crm4.dynamics.com';
$twoUrl = 'https://foobar2.crm4.dynamics.com';

# create connection first CRM instance (production)
$conn1 = Connect-CrmOnline -Credential $credentials -ServerUrl $oneUrl;

$entity = 'lead';
$field = 'description';


# $meta1 = $conn1.GetEntityAttributeMetadataForAttribute($entity, $field);
$meta1 = Get-CrmEntityAttributeMetadata -EntityLogicalName $entity -FieldLogicalName $field -conn $conn1;
Write-Host -ForegroundColor Yellow "Max. Length First CRM Instance: '$($meta1.MaxLength)'" 

# create connection second CRM instance (sandbox)
$conn2 = Connect-CrmOnline -Credential $credentials -ServerUrl $twoUrl;

$conn1.ResetLocalMetadataCache($entity);
$conn2.ResetLocalMetadataCache($entity);

# $meta2 = $conn2.GetEntityAttributeMetadataForAttribute($entity, $field);
$meta2 = Get-CrmEntityAttributeMetadata -EntityLogicalName $entity -FieldLogicalName $field -conn $conn2;
Write-Host -ForegroundColor Yellow "Max. Length Second CRM Instance: '$($meta2.MaxLength)'";
````

I have also tried to update the dlls of for module "Microsoft.Xrm.Data.Powershell" to version "8.2.0.713" but the outcome is still the same.

**Comment by thuld** [comment] 2017-03-08 09:04
It is possible to use the `ResetLocalMetadataCache` method, but with a different notation:

````
$conn1.ResetLocalMetadataCache('lead.description');
$conn2.ResetLocalMetadataCache('lead.description');
````

This will clear the meta-data cache as expected.

**Comment by seanmcne** [comment] 2017-03-20 01:03
Based on the commit (to ensure we have distinctly separate connections per var per process) and the discussion this one appears to be closed out.  Thanks for the help and input as always folks!

**Closed by seanmcne** 2017-03-20 01:03 UTC
Labels: bug
