### ISSUE TITLE
AddCrmUsersFromOU.ps1 error when executing

### ISSUE THREAD

**Issue by mwolfaardt** [seanmcne/Microsoft.Xrm.Data.PowerShell#18] opened 2015-11-27 09:45 UTC
PS C:\scripts>  . .\AddCrmUsersFromOU.ps1
Connecting to CRM OnPremise as singular\sqladministrator
Loading Users from particular OU
Create Crm User on Dynamics CRM OnPremise
WARNING: No Result
Creating CRM User singular.co.za\CRMAdministrator
You cannot call a method on a null-valued expression.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.Xrm.Data.Powershell\Mic
rosoft.Xrm.Data.Powershell.psm1:255 char:9
+         $newfield = New-Object -TypeName 'Microsoft.Xrm.Tooling.Connector.CrmDat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by kenakamu** [comment] 2015-11-27 10:17
Did you update the script parameters? Could you show me how you changed it.

**Comment by mwolfaardt** [comment] 2015-11-27 10:38
yes,

$ouPath = "OU=Crm,DC=contoso,DC=CO,DC=za"
$domainName = "contoso.czz"

$organizationName = "mars-crm"
$serverUrl ="https://mars-crm"
$crmAdminUser = "user1"
$crmAdminPassword = ConvertTo-SecureString -String "P@ssword" -AsPlainText -Force

$securityRoleName = "salesperson"

**Comment by kenakamu** [comment] 2015-11-28 03:00
Thanks,

From the message, seems like passing value is the cause but I want to debug it if you let me.

**Comment by kenakamu** [comment] 2015-12-09 15:44
with no update and this is sample issue not module itself, I will close it.

**Closed by kenakamu** 2015-12-09 15:44 UTC
