### ISSUE TITLE
Intermittent OAuth Access Errors

### ISSUE THREAD

**Issue by albernhagen** [seanmcne/Microsoft.Xrm.Data.PowerShell#131] opened 2016-08-16 14:15 UTC
I'm intermittently receiving this error during the solution import process.  Any ideas or suggestions as to how to resolve it?

```
2016-08-16T13:04:28.4710343Z ##[error]Import-CrmSolution : ImportJob with ID: fb4f3e35-a76f-44c9-8b6b-d96c6112635c has encountered an exception: The HTTP 

2016-08-16T13:04:28.4710343Z ##[error]request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the 

2016-08-16T13:04:28.4710343Z ##[error]server was 'Bearer error=invalid_token, error_description=Error during token validation!, 

2016-08-16T13:04:28.4710343Z ##[error]authorization_uri=https://login.windows.net/guid-to-our-dynamics/oauth2/authorize, 

2016-08-16T13:04:28.4710343Z ##[error]resource_id=https://myorganization.api.crm.dynamics.com/'. 

2016-08-16T13:04:28.4710343Z ##[error]At D:\VSO_Agents\vsoAgent03\_work\5\s\CRMDeploy\Mainline\DeploymentScripts\DeploySolution.ps1:32 char:1

2016-08-16T13:04:28.4710343Z ##[error]+ Import-CrmSolution -conn $conn -SolutionFilePath $solutionFile -publi ...

2016-08-16T13:04:28.4710343Z ##[error]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2016-08-16T13:04:28.4710343Z ##[error]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

2016-08-16T13:04:28.4710343Z ##[error]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-CrmSolution

2016-08-16T13:04:28.4710343Z ##[error] 

2016-08-16T13:04:28.4710343Z ##[error]Import-CrmSolution : System.Management.Automation.RuntimeException: Import result: Job with ID: 

2016-08-16T13:04:28.4710343Z ##[error]fb4f3e35-a76f-44c9-8b6b-d96c6112635c failed at 84.32 percent complete.

2016-08-16T13:04:28.4710343Z ##[error]At D:\VSO_Agents\vsoAgent03\_work\5\s\CRMDeploy\Mainline\DeploymentScripts\DeploySolution.ps1:32 char:1

2016-08-16T13:04:28.4710343Z ##[error]+ Import-CrmSolution -conn $conn -SolutionFilePath $solutionFile -publi ...

2016-08-16T13:04:28.4710343Z ##[error]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2016-08-16T13:04:28.4710343Z ##[error]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

2016-08-16T13:04:28.4710343Z ##[error]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-CrmSolution

2016-08-16T13:04:28.4710343Z ##[error] 
```

**Comment by albernhagen** [comment] 2016-08-22 17:08
Let me know if there's any other info I can provide to help debug this one.

**Comment by seanmcne** [comment] 2016-08-23 16:07
@albernhagen can you run $conn.LastCrmException when this happens?  I wonder if it's potentially a timeout?

**Comment by seanmcne** [comment] 2016-08-23 16:09
@albernhagen, this is very strange, is it possible $conn is not authenticated?  It's saying your bearer token isn't valid as you submitted an anonymous request - that usually wouldn't happen (in fact I don't think it's possible to attempt an anonymous request).  Is $conn established some hours before, maybe it's expiring?  

You may want to try running a fiddler trace at the same time, we could see what the request looks like then.

**Comment by albernhagen** [comment] 2016-08-23 16:13
@seanmcne, it definitely is odd.  The problem is also intermittent.  A little context to our setup -- we have a build job (using TFS) that imports our solution to a dedicated CI environment on an hourly basis throughout the day.  It seems to work a lot of the time but randomly fails.  What's really odd is that it fails in the middle of the import.  It's almost like that access token has changed and it hasn't refreshed for some reason.  Here's one from this morning.

```
2016-08-23T13:00:14.1181009Z VERBOSE: OverwriteCustomizations: True
 
2016-08-23T13:00:14.1190972Z VERBOSE: SkipDependancyCheck: True
 
2016-08-23T13:00:14.1240988Z VERBOSE: Maximum seconds to poll for successful completion: 900
 
2016-08-23T13:00:14.1250979Z VERBOSE: Calling .ImportSolutionToCrm() this process can take minutes...
 
2016-08-23T13:02:14.3710016Z Import of file completed, waiting on completion of importId: 17fa8ca2-6bdd-4458-b0b1-63a4fda927f7
 
2016-08-23T13:02:20.2767472Z 006 seconds of max: 900 ... ImportJob%: 83.67
 
2016-08-23T13:02:25.4434039Z 011 seconds of max: 900 ... ImportJob%: 83.67
 
2016-08-23T13:02:30.6420768Z 016 seconds of max: 900 ... ImportJob%: 83.67
 
2016-08-23T13:03:38.0706372Z ##[error]Import-CrmSolution : ImportJob with ID: 17fa8ca2-6bdd-4458-b0b1-63a4fda927f7 has encountered an exception: The HTTP 
 
2016-08-23T13:03:38.0706372Z ##[error]request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the 
 
2016-08-23T13:03:38.0716434Z ##[error]server was 'Bearer error=invalid_token, error_description=Error during token validation!, 
 
2016-08-23T13:03:38.0716434Z ##[error]authorization_uri=https://login.windows.net/myguid/oauth2/authorize, 
 
2016-08-23T13:03:38.0746432Z ##[error]resource_id=https://myorg.api.crm.dynamics.com/'. 
 
2016-08-23T13:03:38.0746432Z ##[error]At D:\VSO_Agents\vsoAgent03\_work\5\s\CRMDeploy\Mainline\DeploymentScripts\DeploySolution.ps1:32 char:1
 
2016-08-23T13:03:38.0756439Z ##[error]+ Import-CrmSolution -conn $conn -SolutionFilePath $solutionFile -publi ...
 
2016-08-23T13:03:38.0756439Z ##[error]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
2016-08-23T13:03:38.0766358Z ##[error]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
 
2016-08-23T13:03:38.0766358Z ##[error]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-CrmSolution
 
2016-08-23T13:03:38.0776358Z ##[error] 
 
2016-08-23T13:03:38.0776358Z ##[error]Import-CrmSolution : System.Management.Automation.RuntimeException: Import result: Job with ID: 
 
2016-08-23T13:03:38.0776358Z ##[error]17fa8ca2-6bdd-4458-b0b1-63a4fda927f7 failed at 83.67 percent complete.
 
2016-08-23T13:03:38.0786354Z ##[error]At D:\VSO_Agents\vsoAgent03\_work\5\s\CRMDeploy\Mainline\DeploymentScripts\DeploySolution.ps1:32 char:1
 
2016-08-23T13:03:38.0786354Z ##[error]+ Import-CrmSolution -conn $conn -SolutionFilePath $solutionFile -publi ...
 
2016-08-23T13:03:38.0796654Z ##[error]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
2016-08-23T13:03:38.0796654Z ##[error]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
 
2016-08-23T13:03:38.0806392Z ##[error]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-CrmSolution
 
2016-08-23T13:03:38.0806392Z ##[error] 
```

**Comment by seanmcne** [comment] 2016-09-12 13:10
@albernhagen I'm stumped on this one, I reached out to someone to see if he's seen this in the connector before and it didn't sound like he had any ideas off hand - were you able to grab the xrm connector log file from when this happens?  Maybe there's a clue as to what's going on in there. 

The only idea I had that might explain this is if the connection is timed out - there may be some odd pattern when the network connection is dropped if it times out that would cause this false positive to pop up.  Once I get the time I'd like to completely re-write the import function - unfortunately detecting failure and warnings is exceedingly difficult which has added complexity and made this function a bit of a pain at times.

**Comment by albernhagen** [comment] 2016-09-12 15:39
@seanmcne Thanks for helping dig into this.  I haven't grabbed the log file, so it's hard to say exactly what's going on.  One thing we started doing was deleting the token cache file before our process and it seems to be working better.  I'm not convinced that that actually was our real resolution and am inclined to think we're having network issues within our own infrastructure, but it does seem to be working for the time being.  For what it's worth, here's my token cache removal code.

```
# Delete token cache if found
$tokenCacheFileName = "$ENV:UserProfile\AppData\Roaming\Microsoft\CrmConnectPowershell\Default_CrmConnectPowershell.tokens.dat"
If (Test-Path $tokenCacheFileName){
	Remove-Item $tokenCacheFileName
	Write-Output "Deleted token cache file " $tokenCacheFileName
}
else
{
	Write-Output "Token cache file not found " $tokenCacheFileName
}
```

**Comment by seanmcne** [comment] 2016-10-05 16:16
well I have good and bad news, the good & bad news is that I can repro this today. The bad part of that is it's not just an environmental thing on your end and I'm not sure what's causing it yet.  We're looking into it, but it's some kind of false positive.  In fact if you fiddler the request and resubmit it via fiddler the token is accepted so we just need to figure out what's causing the 401 which is bubbling this up.

**Comment by seanmcne** [comment] 2016-10-23 03:39
From what I've been able to deduce this issue may be caused by a timeout taking place in the connector code. To try and mitigate this I added an async import and since using that method I've not been able to repro the problem. Can you try it out (it's now checked in but not yet part of a release).

**Comment by seanmcne** [comment] 2016-11-15 03:22
@albernhagen - I may move to close this now with the async solution import method I've added.  Let me know if you concur or if you've still run into issues.  If you agree with the timeout causing this as a false positive please let me know (to ensure I'm not missing something). 

Thanks!

**Comment by seanmcne** [comment] 2017-01-26 22:59
Hey @albernhagen I'm going to close this for now but let us know if it comes back up again. Thx!

**Closed by seanmcne** 2017-01-26 22:59 UTC
Labels: bug, question
